### ISSUE TITLE
microsoft ntfs by tuxera - files disappearing from usb stick after espelling drive

### ISSUE THREAD

**Issue by mrkapqa** [tuxera/ntfs-3g#100]
Hello ,

i have installed trial version of microsoft ntfs by tuxera on mac os monterey - mac mini (intel) and noticed the following

1. would format under macos the usb stick as "windows nt file system - tuxera ntfs" in "master boot record" and name "test"
2. would transfer .mkv file from nas to usb stick
3. would eject usb stick after completing fully the copying process as shown in tab bar
4. would reinsert usb stick
5. would notice that the file is no longer present on usb stick&

have test this with different usb sticks, same result.

could you please show me where i got it wrong-maybe during the install something went wrong_

installed version is microsoft ntfs by tuxera 2023.1

thank you

**Comment by Tuxera-JamieF** [comment]
Thank you for reaching out.  I have transferred your query to our NTFS for Mac support portal.  You will receive a response shortly.
