### ISSUE TITLE
BUG: NTFS drive corrupted after power failure

### ISSUE THREAD

**Issue by juanpc2018** [tuxera/ntfs-3g#104]
USB3.0 external drive, Thermaltake BlacX 5G,
500GB 2.5" Drive was Writing a Large File. 32GB.img
power was shutdown to the External AC-Adapter.

after reboot, drive had errors, could Not be mounted, 
could Not be Fixed by Kubuntu 22.04.1 LTS Gparted, Nor gnome-disks
had to Reboot in Windows8.1x64 to Scan & Fix, then worked ok.

**Comment by unsound** [comment]
@juanpc2018 Could you post the ```chkdsk``` output from Windows when it repaired the drive? Ideally we'd want an ntfsclone metadata image as well to see what's going wrong but it sounds like you already repaired the problems with the NTFS drive so it is probably too late.

**Comment by unsound** [comment]
Closing this because no further information was provided, so we have nothing to go on.
