### ISSUE TITLE
[Feature Request]FUSE Passthrough?

### ISSUE THREAD

**Issue by RushingAlien** [tuxera/ntfs-3g#114]
Linux 6.9 introduced FUSE passthrough, which will allow better performance for fuse-based filesystems. https://source.android.com/docs/core/storage/fuse-passthrough 

![gambar](https://github.com/tuxera/ntfs-3g/assets/80886145/07d9496a-0ff3-49d6-9733-25c89011e1b2)

I don't know if there is work that needs to be done on the ntfs-3g side to utliize it, but seeing the android documentation, it seems to be a yes.

> When the FUSE daemon receives a request to open a file, it decides whether FUSE passthrough should be available for that particular file. If it's available, the daemon:
> - Notifies the FUSE driver about this request.
> - Enables FUSE passthrough for the file using the `FUSE_DEV_IOC_PASSTHROUGH_OPEN` ioctl, which must be performed on the file descriptor of the opened `/dev/fuse`.

**Comment by jpandre** [comment]
AFAIK this is only possible for a layered file system relying on a kernel-based file system ("lower file system" in the link you referenced)

**Comment by unsound** [comment]
Yes, this is specifically for layered filesystems where the outer layer FUSE daemon can authenticate requests but then allow direct pass-through of read/write requests to the underlying file system. So this feature is not applicable to the ```ntfs-3g``` use case. Closing this...
