### ISSUE TITLE
Good news to see changes in this project

### ISSUE THREAD

**Issue by Neustradamus** [tuxera/ntfs-3g#13]
Dear Tuxera team,

Thanks to have accepted my request!
- https://sourceforge.net/p/ntfs-3g/mailman/message/37226833/

Jean-Pierre André, @jpandre: It is possible to link your email address for your commits with your GitHub account?
- https://github.com/tuxera/ntfs-3g/commits/edge

**Comment by unsound** [comment]
This seems like a personal message rather than an actual issue with the software. Closing this.
