### ISSUE TITLE
we meet "aclocal configure.ac:337: warning: macro 'AM_PATH_LIBGCRYPT' not found in library" about ntfs-3g on ubuntu16.04

### ISSUE THREAD

**Issue by jim-qiu** [tuxera/ntfs-3g#14]
we get code from https://github.com/tuxera/ntfs-3g,the steps are following:
1.  cd  ntfs-3g-edge
2.  aclocal

**Comment by unsound** [comment]
To regenerate the build system you need to install the `libgcrypt-dev` (Debian/Ubuntu) or `libgcrypt-devel` (Fedora/Red Hat) package and run `./autogen.sh`. (In addition `autoconf`, `automake`, `libtool` and `pkg-config` are required.)

**Comment by jpandre** [comment]
Minor addition : encryption libraries are only used by ntfsdecrypt, which very few users need. To avoid encryption library issues, just avoid using the option --with-crypto in the ./configure command.

**Comment by jim-qiu** [comment]
> To regenerate the build system you need to install the `libgcrypt-dev` (Debian/Ubuntu) or `libgcrypt-devel` (Fedora/Red Hat) package and run `./autogen.sh`. (In addition `autoconf`, `automake`, `libtool` and `pkg-config` are required.)

 Afer we run "install the libgcrypt-dev",now we build successfully,thanks.Do you have ntfs-3g for android devices ?
