### ISSUE TITLE
we meet "ntfs-3g-edge/ntfsprogs/utils.c:57:10: fatal error: 'libintl.h' file not found" when we finish porting to android

### ISSUE THREAD

**Issue by jim-qiu** [tuxera/ntfs-3g#15]
we meet "ntfs-3g-edge/ntfsprogs/utils.c:57:10: fatal error: 'libintl.h' file not found" when we finish porting to android

**Comment by unsound** [comment]
Hi, Android support and integration is out of scope for the ```ntfs-3g``` project. However our commercial NTFS offerings do include Android support, so if you're interested then please contact sales@tuxera.com.
