### ISSUE TITLE
macOS Binary on GitHub releases?

### ISSUE THREAD

**Issue by coolaj86** [tuxera/ntfs-3g#20]
Would you upload the Mac binary to GitHub releases?

Most documentation seems to suggest using `brew`, which is terrible because it downloads 400mb of unrelated... whatever-it-is, and it's super slow.

It would be great to have an official, 1st party build directly from the source that can be used safely as a user rather than a 3rd party build that requires sudo, installs in a system location, and has 400mb+ of other dependencies.

😀

**Comment by unsound** [comment]
Hi,

We don't maintain ```ntfs-3g``` binaries but you don't need ```brew``` to build a macOS binary, it can be compiled with macOS standard tools and libraries:
- Download the source bundle and unpack somewhere in your home directory.
- Make sure you have the macOS command line development tools installed (just type 'clang' at the command line... it will ask you to download the tools if you don't have them).
- If you don't have [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) installed then download it, unpack the tarball and build the software with:
```./configure --with-internal-glib && make && sudo make install```
- Install [macFUSE](https://osxfuse.github.io/).
- Open up the terminal, change to the unpacked source bundle and type: ```./configure && make && sudo make install```

For a simple solution with full support and other improvements we of course recommend that you purchase our end-user NTFS solution for macOS (this helps supporting our open source efforts as well):
https://ntfsformac.tuxera.com/
