### ISSUE TITLE
--sbindir ignored

### ISSUE THREAD

**Issue by rofl0r** [tuxera/ntfs-3g#21]
even though --sbindir=/bin is passed, mount.ntfs3g is being installed into /sbin nonetheless.

**Comment by tinywrkb** [comment]
https://github.com/tuxera/ntfs-3g/blob/2021.8.22/src/Makefile.am#L69
```
diff --git a/src/Makefile.am b/src/Makefile.am
index 8d984083..dfe5d457 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -66,9 +66,9 @@ endif

 if ENABLE_MOUNT_HELPER
 install-exec-local:    install-rootbinPROGRAMS
-       $(MKDIR_P) "$(DESTDIR)/sbin"
-       $(LN_S) -f "$(rootbindir)/ntfs-3g" "$(DESTDIR)/sbin/mount.ntfs-3g"
-       $(LN_S) -f "$(rootbindir)/lowntfs-3g" "$(DESTDIR)/sbin/mount.lowntfs-3g"
+       $(MKDIR_P) "$(DESTDIR)$(sbindir)"
+       $(LN_S) -f "$(rootbindir)/ntfs-3g" "$(DESTDIR)$(sbindir)/mount.ntfs-3g"
+       $(LN_S) -f "$(rootbindir)/lowntfs-3g" "$(DESTDIR)$(sbindir)/mount.lowntfs-3g"

 install-data-local:    install-man8
        $(LN_S) -f ntfs-3g.8 "$(DESTDIR)$(man8dir)/mount.ntfs-3g.8"
```

**Comment by unsound** [comment]
IIRC this is by design. Mount helpers can only live in ```/sbin``` which is why this is hard coded, so I'm not sure what you would want to achieve by installing them in, e.g. ```/usr/sbin``` or ```/usr/local/sbin```. If this is no longer the case then could you link to some documentation about this?
You can always configure the software without mount helpers (```--disable-mount-helper```) and create your own links if you're trying to do something custom.

**Comment by tinywrkb** [comment]
@unsound not everyone uses Debian, on Arch Linux `/sbin` is a symlink to `/usr/bin`, and packaging a `/sbin` folder creates a filesystem conflict.

**Comment by unsound** [comment]
@tinywrkb So the problem in mainly the ```MKDIR_P``` line then? Because otherwise as long as there's a ```/sbin``` symlink then the ```--enable-mount-helper``` code should work fine?

**Comment by unsound** [comment]
(Fedora 35 also symlinks ```/sbin``` to ```/usr/sbin``` and installing on Fedora works fine, the ```MKDIR_P``` line doesn't return an error. The manpage of ```mount``` still specifies ```/sbin``` as the only valid location for mount helpers so this is not Debian-specific.)

**Comment by rofl0r** [comment]
it doesn't matter what ubuntu or debian does. some distros do things differently, and if autoconf is used the command line options offered by it should be respected. the patch above fixes the issue for people that know what they're doing, and leaves the default for people that don't.

**Comment by tinywrkb** [comment]
@unsound in Arch Linux, `make install` destination is an empty directory and that is what is being packaged, so if we set configure option `enable-mount-helper`, then a `$DESTDIR/sbin` is created with symlinks.  
I guess the `--disable-mount-helper` option could be used and manually create symlinks, as you suggested. I'll recommend these changes to the maintainer of the Arch Linux ntfs-3d package.

Thanks for replying.

**Comment by unsound** [comment]
You can also leave the mount helper enabled and create the ```/sbin``` symlink in the install location before running ```make install```. Like in this example where the binaries are installed in ```.build``` in the source directory:
```
mkdir -p .build/usr/sbin
ln -sr .build/usr/sbin .build/sbin
make install DESTDIR="`pwd`/.build"
```

Anyway this is really packaging script stuff and every distro does it differently. The generic source bundle is meant to be used for building and installing from source and obviously the ```--sbindir``` location is not appropriate for mount helpers as it's usually ```/usr/sbin``` or ```/usr/local/sbin``` while ```mount``` only looks in ```/sbin``` (the fact that it happens to be a symlink to ```/usr/sbin``` on a particular distro is not something that can be relied on).
The only way to make the mount helper install dir configurable is to add another configure option but really this is stuff that can be worked around easily in packaging scripts so I don't see the point.

**Comment by rofl0r** [comment]
> mount only looks in /sbin

obviously not in distros that don't use sbin.

**Comment by leo60228** [comment]
util-linux has a build-time option to set the search path for mount helpers: https://github.com/util-linux/util-linux/blob/410b261cce8294653c03cb678f61512fa52e81e8/configure.ac#L2599

**Comment by wdlkmpx** [comment]
With autotools you only need to specify certain variables, targets. So basically there's no need to add extensive logic to Makefile.am, otherwise it would be better to add a custom Makefile without autotools

That's the reason I have to apply a patch and rebuild everything 'cause the build system is not suitable for cross compiles
