### ISSUE TITLE
"not in multiple of 0x10000" disk scan errors for sparse files 

### ISSUE THREAD

**Issue by dreamlayers** [tuxera/ntfs-3g#25]
In Ubuntu 21.10 using ntfs-3g 1:2017.3.23AR.3-3ubuntu5 I can create sparse files which result in the following messages from Windows 10 21H2 disk scanning:

Stage 1: Examining basic file system structure ...
The allocated length 0x41000 is not in multiple of 0x10000 for attribute
of type 0x80 and instance tag 0x1.

The Windows GUI will say that the drive was scanned successfully with no errors, and I will need to look in Event Viewer to see this in scanning output. Repeated scans will not do anything about this issue. To fix the issue, make a copy of the affected file in Windows and delete the original.

Attribute of type 0x80 is the data attribute, which tells where the file's data is stored. Apparently Windows allocates space for sparse files in multiples of 64 KB (0x10000), and ntfs-3g does not. The message from disk scanning in Windows fails to tell you what file is involved. I only found the affected file after seeing that sparse files use 64 KB chunks, and then searching the file system for sparse files.

I'm attaching a tar file created with the --sparse option. Extracting it onto NTFS should create a sparse file which triggers this issue. I'm testing with a partition with 4 KB clusters.
[1229312_sparse_266240.tar.gz](https://github.com/tuxera/ntfs-3g/files/7885005/1229312_sparse_266240.tar.gz)

After reporting the Ubuntu bug at https://bugs.launchpad.net/ubuntu/+source/ntfs-3g/+bug/1958180 I tried installing and using ntfs-3g 1:2021.8.22-3ubuntu1 in Ubuntu 21.10, and was able to reproduce the same issue, so I'm reporting it here. I hope this is the right place to report ntfs-3g bugs.

**Comment by jpandre** [comment]
Nothing to be worried about, this is not a bug and the message is just a technical warning. The chkdsk conclusion is "Windows has scanned the file system and found no problems."

Since about 2016, Windows allocates space by chunks of multiple clusters, but it still correctly processes files allocated by a single cluster at a time. You need not make a copy to use it.
