### ISSUE TITLE
bad block size calculated, blksize option ignored

### ISSUE THREAD

**Issue by Deiv70** [tuxera/ntfs-3g#27]
# ntfs-3g gets bad BlockSize and doesn't let me use the real BS

First of all, congrats :confetti_ball: to the team for the effort into this really great tool that provides a easy way to handle NTFS filesystems :100: 

Now, the problem I faced...
I have a partition of ***2 MB*** BS, but ntfs-3g mounts it as it's the default (***4KB***), despite the fact that ***ntfsinfo*** (which I thought would be where it should get the value as it was ported to ntfs-3g) gives the right value **`Cluster Size: 2097152`**.

I tried to use the ***-o blksize=2097152*** option, but i get the error: `WARNING: blksize option is ignored because ntfs-3g must calculate it.`

Please, could someone tell me how I can use the correct Block Size?  :smiling_face_with_tear: 

Lastly, I would like to say that I think in the future the behavior of using the **ntfsinfo** *Cluster Size* would improve/fix this. :+1:

**Comment by jpandre** [comment]
> Please, could someone tell me how I can use the correct Block Size?

You probably do (depends on what you mean by block size). The cluster size is the unit of disk space allocation. In your case this is 2MiB. When stored in memory, a cluster is sliced into system pages, and when read or written to disk it has to be sliced into sectors.

ntfs-3g uses the cluster size shown by ntfsinfo when it requests the system to read or write user data. It cannot prevent the lower levels to use their own buffer sizes.
`getconf PAGE_SIZE`
returns the system page size, and
`fdisk -l`
shows the disk sector size

Note : big clusters are inefficient when the application use smaller buffers.

EDIT : I forgot the intermediate slicing by fuse, which you can dissociate from page size, up to some builtin system limit, by using the mount option "big_writes".
