### ISSUE TITLE
lsattr always return random flags on ntfs mount

### ISSUE THREAD

**Issue by Tachiorz** [tuxera/ntfs-3g#28]
lsattr always return random flags on ntfs mount, randomly breaking wine software because of EXT4_CASEFOLD_FL flag.

**Comment by jpandre** [comment]
lsattr is not supported, and the error (EINVAL) may be poorly returned.
1) mounting with lowntfs-3g instead of ntfs-3g may fix this,
2) what is the output of :
`ntfs-3g -help 2>&1 | grep ration`

**Comment by Tachiorz** [comment]
```
ntfs-3g 2021.8.22 external FUSE 29 - Third Generation NTFS Driver
                Configuration type 7, XATTRS are on, POSIX ACLS are on
```
This might be a kernel issue, I tried booting into 5.10.52 and got 
`lsattr: Invalid argument While reading flags`
Bug with random flags manifested itself on 5.15.16

**Comment by jpandre** [comment]
I do not think this to be a kernel issue. It may be a fuse issue in the high level interface (I have to sync with the fuse maintainer to be sure). It does not happen when using the fuse low level interface or using the fuse interface internal to ntfs-3g.

Until this is clarified, the easiest workaround is to mount the ntfs partition with lowntfs-3g instead of ntfs-3g. Just replace ntfs-3g by lowntfs-3g in the third field of /etc/fstab or in the -t option of the mount command.

Note the returned message "Invalid argument While reading flags..." is what is expected. lsattr(1) issues an ioctl(2) which is supposed to return EINVAL for an unsupported feature.

**Comment by jpandre** [comment]
Searching deeper, I could not find a way to get lsattr(1) to return anything. In all tested configurations it returns with an EINVAL error ("Invalid argument etc.") as expected for an unsupported ioctl(2) feature.

Are you sure you get some flags ? How is the error processed in your situation ?

**Comment by Tachiorz** [comment]
I was looking for a reason why wine can't find dlls named in a different case and it was because it was testing directory for case sensitivity and deemed it case insensitive
```
    if (ioctl( fd, EXT2_IOC_GETFLAGS, &flags ) != -1 && (flags & EXT4_CASEFOLD_FL))
    {
        sens = FALSE;
    }
```
That was weird, I tested directory with lsattr (e2fsprogs-1.46.4) and got weird results:
![Screenshot_2022-02-05_21-05-20](https://user-images.githubusercontent.com/62375/152694448-9ee15c35-4c52-4094-b0e9-7569a36829e3.png)
I tried to boot older 5.10 kernel and got Invalid argument as expected. I tried to recompile 5.15 and play with options, but got random flags anyway.
I can try to debug it, but I never debugged ioctls and don't know which functions to look at

**Comment by jpandre** [comment]
When using kernel 5.15, are you sure you are using ntfs-3g at all ? Is there an ntfs-3g process ?

**Comment by Tachiorz** [comment]
Yes, I got ntfs-3g in fstab and there are /sbin/mount.ntfs-3g processes.

**Comment by jpandre** [comment]
Please make a try with lowntfs-3g (the mount process will be /sbin/mount.lowntfs-3g) with kernel 5.15. I would like to clarify whether the oddity on the fuse interface has anything to do with the issue.

**Comment by Tachiorz** [comment]
With lowntfs-3g lsattr returns Invalid argument
![Screenshot_2022-02-07_16-36-58](https://user-images.githubusercontent.com/62375/152808868-adcd9b44-6ca7-4230-ad11-87d2a6baf41c.png)

**Comment by jpandre** [comment]
So, using lowntfs-3g must be the easiest workaround, until we get feedback from the fuse experts. Another option is to recompile ntfs-3g with its own fuse library (which is the default option).

**Comment by Tachiorz** [comment]
I found that "unstable" package of ntfs3g has internal fuse library enabled and it works fine on 5.15. Invalid argument as expected.
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/ntfs3g/ntfs3g-2021.8.22-r3.ebuild#n65
