### ISSUE TITLE
Clean up old/unused branches?

### ISSUE THREAD

**Issue by ratijas** [tuxera/ntfs-3g#3]
There are some really obsolete branches in the repository, including `master` branch. How about deleting them?

![Branches](https://user-images.githubusercontent.com/6737986/122055946-cd4b2b00-cdf1-11eb-9f10-3b698d47b749.png)

**Comment by unsound** [comment]
First of all, the edge.strict_endians branch is not obsolete so it should not be in this list. The others mostly mark transition points between past development phases.
I don't see any reason to remove them, they still provide useful guidance info when navigating through the repository history.

**Comment by ratijas** [comment]
But there's like... tags for marking historical points, right?

**Comment by unsound** [comment]
Closing issue as this suggestion is of no benefit for the maintainers of the repository.
