### ISSUE TITLE
It should be possible to cancel mkfs.ntfs

### ISSUE THREAD

**Issue by naoliv** [tuxera/ntfs-3g#30]
Example:

```
# mkfs.ntfs /dev/sdc1 
Cluster size has been automatically set to 4096 bytes.
Initializing device with zeroes:   4%^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

And no matter how many `Ctrl+C` I press, it keeps creating the filesystem on the disk.
Shouldn't `mkfs.ntfs` stop after a `Ctrl+C`? Isn't it possible to capture `SIGINT` and stops whatever `mkfs.ntfs` is doing, please?

`ntfs-3g` is Debian's `2021.8.22-3`
Linux kernel is `5.15.15`

Thanks!

**Comment by jpandre** [comment]
mkntfs (aka mkfs.ntfs) keeps all the signals settings as default. There must be another reason.

**Comment by naoliv** [comment]
I don't know if this helps at all, but I can reproduce this when trying to create the filesystem on a USB stick.

**Comment by jpandre** [comment]
A USB stick is slow so, most likely, the image grows into memory much faster than it can make it to the stick. When you hit Ctrl-C, filling the memory may stop, but this does not halt the flow from memory to the stick, and mkntfs cannot do anything about it.
