### ISSUE TITLE
Where does UltraDefrag beta test (udefrag) development go?

### ISSUE THREAD

**Issue by Unknown78** [tuxera/ntfs-3g#31]
https://web.archive.org/web/20210830161447/https://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html
According to way back machine, the download link for the Ultra Defrag is still available.
But, will the development be continued or we just stuck with [ultradefrag-5.0.0AB.8.zip](https://jp-andre.pagesperso-orange.fr/ultradefrag-5.0.0AB.8.zip)?

I couldn't find any description available on the google, github or tuxera on where the development go. It just suddenly vanished between 30th August 2021 and 13th October 2021. This development is the only and currently reliable ntfs defragment port/software in unix/unix-like system that I know and valued so much.

**Comment by jpandre** [comment]
The initial porting of Ultradefrag was made ten years ago, and there has been no request and no test report for years, so it is stalled in a beta test state.

In the meantime, the original Ultradefrag for Windows went through major modifications, and the porting should be started over.

The [ultradefrag-5.0.0AB.8.zip](https://jp-andre.pagesperso-orange.fr/ultradefrag-5.0.0AB.8.zip) file is still available for download, and the steps for doing the port to linux/unix from an original Windows version are documented within. This is just waiting for somebody to undertake the job, but with a limited level of demand, I am afraid there is no much hope a newer Ultradefrag port surfaces again.
