### ISSUE TITLE
Memory leak/logic bug in ntfsusermap.c:callback

### ISSUE THREAD

**Issue by Teemperor** [tuxera/ntfs-3g#32]
The `callback` function seems to leak memory (to be specific, the `accname` string is getting leaked here). There also might be some kind of logic bug here as `accname` is created and then filled with the contents of `name`, but then never used for anything.

https://github.com/tuxera/ntfs-3g/blob/92b9fbc6fe5aaa940a401b8f5ff2ed8cac6d5cc6/ntfsprogs/ntfsusermap.c#L625-L634

**Comment by jpandre** [comment]
You are right, this accname variable is not needed. This will be fixed in the next release.
Thanks for the report.
