### ISSUE TITLE
configure issue on m1 Mac? please help

### ISSUE THREAD

**Issue by caixiaomin** [tuxera/ntfs-3g#37]
➜  ntfs-3g git:(edge) ./autogen.sh
Running autoreconf --verbose --install --force
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:337: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
glibtoolize: Remember to add 'LT_INIT' to configure.ac.
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
configure.ac:337: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf --force
configure.ac:189: warning: The macro `AC_GNU_SOURCE' is obsolete.
configure.ac:189: You should run autoupdate.
./lib/autoconf/specific.m4:312: AC_GNU_SOURCE is expanded from...
configure.ac:189: the top level
configure.ac:475: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:475: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:475: the top level
configure.ac:246: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:337: error: possibly undefined macro: AM_PATH_LIBGCRYPT
configure.ac:342: error: possibly undefined macro: AC_MSG_WARN
autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

**Comment by unsound** [comment]
The warning indicates that you don't have the libgcrypt autoconf macros. This is not m1- or Mac-specific, you need to have the necessary prerequisites.
Note that if you unpack and configure from the release's tarball you won't need any of this, you can just unpack, configure and make. The git repository is meant for developers, the tarball for end users so if you're just looking to compile and use ```ntfs-3g``` you should download the tarball instead:
https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2021.8.22.tgz
