### ISSUE TITLE
Compiling on macOS BigSur

### ISSUE THREAD

**Issue by matteodefinis** [tuxera/ntfs-3g#5]
Hi I'm trying to compile tuxera's ntfs-3g by myself because homebrew has blocked all packages requiring FUSE.

So I tried these commands: `git clone https://github.com/tuxera/ntfs-3g.git ./autogen.sh ./configure make`

but when running make it begins to compile but at the end it reports that: `Undefined symbols for architecture x86_64: "_libintl_setlocale", referenced from: _utils_set_locale in utils.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make[2]: *** [ntfsfix] Error 1 make[1]: *** [all-recursive] Error 1 make: *** [all] Error 2`

How can I solve that?

**Comment by unsound** [comment]
I think this is a problem with your local headers and libraries. It's looking for `libintl_setlocale` but `libintl.h` is not present in Xcode's SDKs so you must have installed `libintl` manually. However the library cannot be found in the library search paths. With only Xcode's SDK and no user-installed third party headers there's no problem compiling on Big Sur. Please check your `/usr/local` directory for any clues.

**Comment by sryze** [comment]
I have `/usr/local/lib/libintl.a` installed by Homebrew via `brew install gettext` (version 0.21)

Should I remove it to build ntfs-3g? Or give it some clue on where to find the lib?

Update:

This fixed it in my case:

```
LDFLAGS="-L/usr/local/lib -lintl" ../configure
```

**Comment by themightyoarfish** [comment]
Same issue here, seems like the build script does not look for libintl correctly.
