### ISSUE TITLE
Support for Windows Bitlocker in Linux through ntfs-3g

### ISSUE THREAD

**Issue by milkywaymetropolis** [tuxera/ntfs-3g#50]
I was transferring files to and from a bitlocker partition in linux. PC was slowing down while transferring. Does it support bitlocker fully, i.e. on the fly encryption. I have a little doubt on this.

Anyone with similar issue?

Currently I can open bitlocker partition in linux. Pls help with the issue/doubt.

Best regards

**Comment by unsound** [comment]
Hi,

Bitlocker is not NTFS, it's a completely different storage layer. You are probably using dislocker ( https://github.com/Aorimn/dislocker ) to access your Bitlocker partition? Please report any performance issues to that project.

**Comment by yoshimo** [comment]
CryptSetup also got support for bitlocker not too long ago in 2.3.0
