### ISSUE TITLE
FETCH_HEAD detected as folder, then cant delete using rm or rm -rf or rmdir and cant move using mv (ntfs file system). must delete from windows os.

### ISSUE THREAD

**Issue by masWahyuBayuAji** [tuxera/ntfs-3g#53]
![image](https://user-images.githubusercontent.com/111325672/184776408-610094d7-cc15-4abc-98cf-b371fe568d2f.png)
![image](https://user-images.githubusercontent.com/111325672/184777216-aeb21b56-4e11-4120-85be-a84c5aec1510.png)
![image](https://user-images.githubusercontent.com/111325672/184777413-a86cd55e-cfc7-4d62-8e3f-c7b62605d4a0.png)

**Comment by jpandre** [comment]
Must be time you start a chkdsk

**Comment by unsound** [comment]
At the very least we'd need a way to reproduce this in order to investigate it. ```chkdsk``` output might also be helpful but in the absence of these things we can't investigate this. I'm therefore closing. Feel free to reopen if there's more info available.
