### ISSUE TITLE
How can I open OneDrive folder?

### ISSUE THREAD

**Issue by GerardPolloRebozado** [tuxera/ntfs-3g#60]
I have dual boot on my computer and I need to enter in my one drive folder from my windows partition.

I saw some links to a plugin download but they don't work, some of them tell me to look on this github.

**Comment by ruslaniv** [comment]
I have the same problem

**Comment by ashurling-cas** [comment]
I found working copies of plugin on Wayback Machine. https://web.archive.org/web/20210818075848/https://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html . I don't know if there is a new location for these files. This is the discussion where I found this info https://bugs.launchpad.net/ubuntu/+source/ntfs-3g/+bug/1728354
