### ISSUE TITLE
Migration from Sourceforge is not complete

### ISSUE THREAD

**Issue by Neustradamus** [tuxera/ntfs-3g#63]
Dear @tuxera team, @jpandre,

It will be nice to remove old parts like:
- https://sourceforge.net/p/ntfs-3g/cvs/
- https://sourceforge.net/p/ntfs-3g/_list/git
- https://sourceforge.net/p/ntfs-3g/ntfs-3g/ci/edge/tree/
- https://sourceforge.net/p/ntfs-3g/old_ntfs-3g_ntfsprogs/ci/PERMISSION_HANDLING_BRANCH/tree/
- https://sourceforge.net/p/ntfs-3g/pjd-fstest/ci/master/tree/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/projects/ntfs-3g/

To disable/delete tabs, go here: https://sourceforge.net/projects/ntfs-3g/
To add a new tab, go here: https://sourceforge.net/projects/ntfs-3g/
To change informations, go here: https://sourceforge.net/p/ntfs-3g/admin/overview
To export, go here: https://sourceforge.net/p/ntfs-3g/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/ntfs-3g/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/ntfs-3g/admin/overview
- A new tab, go here: https://sourceforge.net/projects/ntfs-3g/

The website link is not good in Sourceforge options (better to change with github.com too):
- http://www.tuxera.com/community/ntfs-3g-download/

Thanks in advance.

**Comment by unsound** [comment]
Hi,

The intention is to keep sourceforge stuff around to avoid breaking old external links. We could maybe communicate better that the sourceforge project is there for archival purposes only, and that any new development is done in github.

**Comment by Neustradamus** [comment]
@unsound: It is for this that I have specified a complete good ticket here with an explanation and steps.
Sourceforge project is not closed, the https://sourceforge.net/projects/ntfs-3g/ will work.
A lot of people think that it is a dead project.

**Comment by unsound** [comment]
@Neustradamus Thanks for the suggestions. What I have done is to add a notice to the Sourceforge project description that development continues on GitHub, marked it as a moved project with a GitHub link and changed the support URL to point at the GitHub issues page. I hope that's clear enough.

**Comment by Neustradamus** [comment]
@unsound: Thanks!

But you have forgotten to remove:
- https://sourceforge.net/p/ntfs-3g/cvs/
- https://sourceforge.net/p/ntfs-3g/_list/git
- https://sourceforge.net/p/ntfs-3g/ntfs-3g/ci/edge/tree/
- https://sourceforge.net/p/ntfs-3g/old_ntfs-3g_ntfsprogs/ci/PERMISSION_HANDLING_BRANCH/tree/
- https://sourceforge.net/p/ntfs-3g/pjd-fstest/ci/master/tree/

**Comment by unsound** [comment]
@Neustradamus There's no intention to remove old VCS content. As I said earlier, older scripts may depend on them and there's no reason to break things just because we can.
