### ISSUE TITLE
New Changelog location?

### ISSUE THREAD

**Issue by attritionorg** [tuxera/ntfs-3g#7]
https://github.com/tuxera/ntfs-3g/blob/edge/ChangeLog

References:
Detailed ChangeLog can be found at
	http://www.tuxera.com/community/release-history/
The changes and history may also be found on the source repository :
	http://sourceforge.net/p/ntfs-3g/ntfs-3g/ci/edge/tree/

The first is no longer there. The second is the same content as quoted, so a self-referencing file unless that is meant to mean the commit history.

**Comment by unsound** [comment]
We're currently working on updating documentation, so please be patient. Some of it has already been migrated to the github wiki system:
https://github.com/tuxera/ntfs-3g/wiki

**Comment by unsound** [comment]
Closing this as the documentation has been updated to point at github.
