### ISSUE TITLE
Is there any patent issue for using ntfs-3g?

### ISSUE THREAD

**Issue by balisa** [tuxera/ntfs-3g#75]
There seems to be a lot of patent issues from Microsoft related to NTFS, so I have a few questions about it.
I would like to take the source code from https://github.com/tuxera/ntfs-3g, add some functions, and distribute the source code under GPL-2.0 to another repository. Is there a patent issue?
Also, I would like to ask if there is a patent issue when using the Source Code that I distributed in product.

**Comment by Artoria2e5** [comment]
NTFS is very likely too old to have any patent issue. NTFS-3G has been used by Linux distributions as commodified as Ubuntu and as far as I can tell they have not bumped into any issue of that kind. Taxer has been selling a commercial version with no issue too.

> Something about doing stuff to this source code

Well, all I can tell you wrt GPL is that it frees you from any patents held by the writer of the code. It does not free you from Microsoft.

**Comment by unsound** [comment]
Closing this issue because it's a question that should be directed to the likely patent owner of patents that could apply to NTFS-related technologies, if any (i.e. probably Microsoft). It's not something that the authors of this project can answer with any legal authority.
