### ISSUE TITLE
NTFS-3G priority to NTFS3?

### ISSUE THREAD

**Issue by Firestar-Reimu** [tuxera/ntfs-3g#79]
I am using archlinux and linux6.2.12 with Paragon Software NTFS3 enabled

But NTFS3 cannot mount **dirty** NTFS partitions

![Screenshot_20230421_162620](https://user-images.githubusercontent.com/65082432/233588059-5ee4335e-fe74-40ba-bcd9-014676576449.png)

(test on linux-6.2.11 dolphin-22.12.3-1)

So I downloaded `ntfs-3g`:

```
$ sudo ntfsfix --no-action /dev/sda
Mounting volume... NTFS signature is missing.
FAILED
Attempting to correct errors... NTFS signature is missing.
FAILED
Failed to startup volume: Invalid argument
NTFS signature is missing.
Trying the alternate boot sector
Unrecoverable error
Volume is corrupt. You should run chkdsk.
No change made
```

After running `sudo ntfsfix /dev/sda1`:
```
$ sudo ntfsfix /dev/sda1
Mounting volume... OK
Processing of $MFT and $MFTMirr completed successfully.
Checking the alternate boot sector... OK
NTFS volume version is 3.1.
NTFS partition /dev/sda1 was processed successfully.
```

It can be mounted, but I don't know if it is mounted by `ntfs3` or `ntfs-3g`

So:

1. If I download ntfs-3g, will it have a higher priority to ntfs3?
2. Can a version of only `ntfsfix` but no `ntfs-3g` be provided?

**Comment by unsound** [comment]
> 1. If I download ntfs-3g, will it have a higher priority to ntfs3?

This is a distribution-specific question as we have no control over the priority used when the system selects drivers for mounting NTFS filesystems. You should ask in Arch Linux forums.

> 2. Can a version of only ntfsfix but no ntfs-3g be provided?

If you are compiling ```ntfs-3g``` by yourself there is the ```--disable-ntfs-3g``` configure option which builds ```libntfs-3g``` and the ```ntfsprogs``` but not the ```ntfs-3g``` FUSE driver itself. If you using a standard package from your distribution you should again ask this question in Arch Linux forums.

**Comment by Firestar-Reimu** [comment]
Thanks, I found an AUR package [ntfsprogs-ntfs3](https://aur.archlinux.org/packages/ntfsprogs-ntfs3) which disabled ntfs-3g
