### ISSUE TITLE
error when mounting a usb flash drive (15:15:33 kernel: ntfs3: sdb1: volume is dirty and "force" flag is not set!)

### ISSUE THREAD

**Issue by saber716rus** [tuxera/ntfs-3g#88]
the essence of the problem. the usb flash drive does not want to be mounted.

15:15:33 kernel: ntfs3: sdb1: volume is dirty and "force" flag is not set!

https://termbin.com/mbdtx
[cообщения журнала.txt](https://github.com/tuxera/ntfs-3g/files/11781461/c.txt)
Bus 001 Device 006: ID 1005:b113 Apacer Technology, Inc. Handy Steno/AH123 / Handy Steno 2.0/HT203

**Comment by unsound** [comment]
Hi, the output is from the ```ntfs3``` kernel driver, not from ```ntfs-3g```, which is the userspace driver. So wrong project, please report your bug to the ```ntfs3``` developers.
