### ISSUE TITLE
GPL License violation?

### ISSUE THREAD

**Issue by johnothwolo** [tuxera/ntfs-3g#92]
I've noticed that Apple's Ntfs driver basically ntfs-3g in the kernel. However, they have an APSL license file in their repository. This is a problem because some ntfs3g files have this:

```  C 
/*
 * ...
 * See LICENSE file for licensing information.
 * ...
 * */
```

This looks to me like a licensing violation on Apple's part.

**Comment by unsound** [comment]
Hi, this is no violation. First of all their driver isn't actually derived from ntfs-3g (but they share some common ancestry) and second Apple has a separate agreement with the authors of the code included in their products.

**Comment by johnothwolo** [comment]
Alright, I just wanted clarification from the authors. I assumed this was the place to ask about this because according to the NTFS wiki, Apple allegedly hired a key figure from Tuxera to write their driver about 1.5 decades ago. I guess it's an Apple problem.
