### ISSUE TITLE
ntfsresize uses only 1 core

### ISSUE THREAD

**Issue by tmollov** [tuxera/ntfs-3g#93]
Hi,

When i was using **_Gparted_** i noticed that 
**ntfsresize** is running only on _single core_ so i wanted to ask: is that how it supposed to work like?

**Comment by unsound** [comment]
This is completely expected, and I would expect other offline resize utilities to work the same. This type of work is typically I/O bound and not CPU bound and I wouldn't expect much of an improvement attempting to parallelize the workload.
