### ISSUE TITLE
configure error: ntfs-3g can be built for Linux, FreeBSD, Mac OS X, NetBSD, and Solaris only.

### ISSUE THREAD

**Issue by xzoogen** [tuxera/ntfs-3g#98]
on linux mint 21.2, i want to build `ntfsusermap.exe` 
according to Readme and  `INSTALL` inside release file `ntfs-3g_ntfsprogs-2022.10.3` run
```sh
./configure --enable-extras --enable-posix-acls --enable-xattr-mappings --build=mingw64
```

But got the follow ERROR:

```bash
S ~/Downloads/ntfs-3g_ntfsprogs-2022.10.3
 % ./configure --enable-extras --enable-posix-acls --enable-xattr-mappings --build=mingw64
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking target system type... x86_64-pc-mingw64
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes

...
...
...

checking for sed... (cached) /usr/bin/sed
checking for ldconfig... /sbin/ldconfig
checking Windows OS... no
checking fuse compatibility... configure: error: ntfs-3g can be built for Linux, FreeBSD, Mac OS X, NetBSD, and Solaris only.

```

**Comment by xzoogen** [comment]
solved by linux `ntfsusermap`
first umount ntfs disk, then run

```
id
sudo ntfsusermap /dev/sdb4
```
after generate 


* You will have to move the file "UserMapping"
  to directory ".NTFS-3G" after mounting

[/etc/fstab example](https://github.com/tuxera/ntfs-3g/wiki/File-Ownership-and-Permissions#mount-options)
```
# mount a hard disk, with new files getting their protections
# the Windows way (a UserMapping file is required)
mount -t ntfs-3g -o inherit /dev/sda3 /mnt/shared
```

**Comment by CodingKoopa** [comment]
Just to clarify for anyone else stumbling on this issue: this error message is correct, since the driver part isn't supposed to work on Windows. You can get around this by passing the `--disable-ntfs-3g` argument to `./configure`.

I have contributed some fixes for the Windows build in https://github.com/tuxera/ntfs-3g/pull/106.
